language: php

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env:
        - COMPOSER_FLAGS="--prefer-lowest --prefer-dist --no-interaction"
    - php: 5.6
    - php: 7.0
      env:
        - COMPOSER_FLAGS="--prefer-lowest --prefer-dist --no-interaction"
    - php: 7.0
    - php: 7.1
      env:
        - COMPOSER_FLAGS="--prefer-lowest --prefer-dist --no-interaction"
    - php: 7.1
      env:
        - CODE_COVERAGE=true

install:
   - composer self-update
   - composer update $COMPOSER_FLAGS
   - composer info

script:
   - vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover=coverage.clover

after_script:
  - if [[ $CODE_COVERAGE == 'true' ]]; then wget https://scrutinizer-ci.com/ocular.phar ; fi
  - if [[ $CODE_COVERAGE == 'true' ]]; then php ocular.phar code-coverage:upload --access-token="230ec5e01daf5bb3e46ea304fb20348b52d80de73463ec08ee9c96fcd1349e35" --format=php-clover coverage.clover ; fi

cache:
  directories:
  - "$HOME/.composer/cache"
